---
services:
  metaminter-monorepa-db:
    container_name: ${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-db
    image: mongo:4.4
    restart: unless-stopped
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ${DATABASE_PATH}/${CI_PROJECT_NAME}/${CI_COMMIT_BRANCH}:/data/db
    networks:
      - app-net

  metaminter-monorepa-backend:
    image: ${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}-backend:${CI_COMMIT_BRANCH}
    container_name: ${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-backend
    restart: unless-stopped
    environment:
      JWT_ALGORITHM: "${JWT_ALGORITHM}"
      JWT_EXPIRES_IN: "${JWT_EXPIRES_IN}"
      JWT_SECRET: "${JWT_SECRET}"
      MONGODB_URL: "mongodb://${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-db:27017/${CI_PROJECT_NAME}"
      BOT_TOKEN: "${BOT_TOKEN}"
      BOT_NAME: "${BOT_NAME}"
      NODE_ENV: "${NODE_ENV}"
      APP_URL: "https://api.${PROJECT_URL}"
      CLOUDFLARE_DOMAIN: "$CLOUDFLARE_DOMAIN"
      CLOUDFLARE_ACCESS_KEY_ID: "$CLOUDFLARE_ACCESS_KEY_ID"
      CLOUDFLARE_SECRET_ACCESS_KEY: "$CLOUDFLARE_SECRET_ACCESS_KEY"
      CLOUDFLARE_BUCKET_NAME: "$CLOUDFLARE_BUCKET_NAME"
      CLOUDFLARE_R2_ENDPOINT: "$CLOUDFLARE_R2_ENDPOINT"

    labels:
      - traefik.enable=true
      - traefik.http.routers.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-backend.entrypoints=websecure
      - traefik.http.routers.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-backend.rule=Host(`api.${PROJECT_URL}`)
      - traefik.http.routers.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-backend.tls=true
      - traefik.http.routers.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-backend.tls.certresolver=letsencrypt
      - traefik.http.services.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-backend.loadbalancer.server.port=3002
    depends_on:
      - metaminter-monorepa-db
    networks:
      - traefik
      - app-net

  metaminter-monorepa-frontend:
    image: ${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}-frontend:${CI_COMMIT_BRANCH}
    container_name: ${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-frontend
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-frontend.entrypoints=websecure
      - traefik.http.routers.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-frontend.rule=Host(`app.${PROJECT_URL}`)
      - traefik.http.routers.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-frontend.tls=true
      - traefik.http.routers.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-frontend.tls.certresolver=letsencrypt
      - traefik.http.services.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-frontend.loadbalancer.server.port=80
    depends_on:
      - metaminter-monorepa-backend
    networks:
      - traefik

networks:
  traefik:
    external: true
  app-net:
    name: ${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-net
    driver: bridge